name: build flannel

on: [push, pull_request]

env:
  GO_VERSION: "1.17.2"
  LINUX_ARCHES: "amd64 arm arm64 s390x ppc64le mips64le"

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: go mod vendor
        run: go mod vendor

      - name: build linux
        run: |
          set -e
          for arch in ${LINUX_ARCHES}; do
            echo "Building for arch $arch"
            ARCH=$arch make dist/flanneld-$arch
            file dist/flanneld-$arch
          done

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image for amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.amd64
          push: false

      - name: Build Docker image for arm
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.arm
          push: false

      - name: Build Docker image for arm64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.arm64
          push: false

      - name: Build Docker image for s390x
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.s390x
          push: false

      - name: Build Docker image for ppc64le
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ppc64le
          push: false

      - name: Build Docker image for mips64le
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.mips64le
          push: false
