name: e2e tests for flannel

on: [push, pull_request]

jobs:
  e2e-test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run tests
      run: git fetch --all --tags && make test

